In [1]:
"""=============================================================================
    Ex1: DECOMPOSITION
    Câu 3: QA Decomposition
        a) Tạo ma trận A(4 x 4) chứa các giá trị ngẫu nhiên trong khoảng 5 - 10
        b) Phân tích thành các thành phần Q và R. In kết quả
        c) Tái tạo lại ma trận A từ các thành phần Q và R
============================================================================="""
    
import numpy  as np
import random       
from scipy.linalg import qr

##------------------------------------------------------------------------------
## Hàm tạo 1 ma trận A[mxn] với giá trị ngẫu nhiên thuộc [start, end]
##------------------------------------------------------------------------------
def create_matrix_random(m, n, start, end):
    mtr = []
    for i in range(m):
        row = []
        for j in range(n):
            a = random.randint(start, end + 1)
            
            # Thêm giá trị vào dòng hiện hành 
            row.append(a)
            
        # Thêm dòng vào ma trận    
        mtr.append(row)
        
    return np.array(mtr)
##------------------------------------------------------------------------------

## a) Tạo ma trận A(4 x 4) chứa các giá trị ngẫu nhiên trong khoảng 5 - 10
m, n, min, max = 4, 4, 5, 10
A = create_matrix_random(m, n, min, max)
print('Ma trận A', A.shape, ':\n', A)

## b) Phân tích thành các thành phần Q và R. In kết quả
Q, R = qr(A)

print('Ma trận Q', Q.shape, ':\n', Q)
print('Ma trận R', R.shape, ':\n', R)

## c) Tái tạo lại ma trận A từ các thành phần Q và R
print('Tái tạo ma trận A:\n', Q.dot(R))


Ma trận A (4, 4) :
 [[ 7  8  7  6]
 [ 9 10  5  5]
 [10 10 11 10]
 [11  8  8 10]]
Ma trận Q (4, 4) :
 [[-0.37363236 -0.41974794 -0.22630487 -0.79561086]
 [-0.48038446 -0.45011269  0.70553871  0.2623823 ]
 [-0.53376051 -0.15182372 -0.6522905   0.51630066]
 [-0.58713656  0.77340791  0.15974461 -0.17774285]]
Ma trận R (4, 4) :
 [[-18.734994   -17.82760112 -15.58580697 -15.85268723]
 [  0.          -3.19008435  -0.67159671   1.44679078]
 [  0.           0.          -3.95367917  -2.75559457]
 [  0.           0.           0.          -0.07617551]]
Tái tạo ma trận A:
 [[ 7.  8.  7.  6.]
 [ 9. 10.  5.  5.]
 [10. 10. 11. 10.]
 [11.  8.  8. 10.]]
