In [1]:
"""============================================================================
   a) Slide #14 
      A = L.LT = UT.U
         L: ma trận tam giác DƯỚI, khả nghịch, Lii > 0
         U: ma trận tam giác TRÊN, khả nghịch, Uii > 0
    b) Kiểm tra tính chất POSITIVE DEFINITE, POSITIVE SEMIDEFINITE
============================================================================"""
import numpy as np

from numpy        import linalg   as la
from scipy.linalg import cholesky

# from numpy.linalg import cholesky: Default --> LOWER


#------------------------------------------------------------------------------
# Positive definite (SYMETRIC) matrix
#------------------------------------------------------------------------------
A = np.array([[6, 1, 1], 
              [1, 6, 1], 
              [1, 1, 6]])

# Cholesky decomposition: Default --> UPPER (U)
U = cholesky(A)
print("UPPER   Cholesky factor:\n", U)
print("A:\n", U.T.dot(U))

U = cholesky(A, lower = False)
print("UPPER   Cholesky factor:\n", U)

L = cholesky(A, lower = True)
print("LOWER   Cholesky factor:\n", L)
print("A:\n", L.dot(L.T))


#------------------------------------------------------------------------------
# Positive definite (NON-SYMETRIC) matrix
#------------------------------------------------------------------------------
A = np.array([[  4,  12, -15], 
              [ 12,  37, -42], 
              [-16, -43,  98]])

# Cholesky decomposition
U = cholesky(A)
print("UPPER   Cholesky factor:\n", U)
print("A:\n", U.T.dot(U))

U = cholesky(A, lower = False)
print("UPPER   Cholesky factor:\n", U)

L = cholesky(A, lower = True)
print("LOWER   Cholesky factor:\n", L)
print("A:\n", L.dot(L.T))


"""----------------------------------------------------------------------------
   Kiểm tra tính chất POSITIVE DEFINITE của ma trận A
----------------------------------------------------------------------------"""
# Positive DEFINITE (symmetric) matrix
A = np.array([[9, 6], 
              [6, 5]])

# Eigenvalues
eigenValues, eigenVectors = la.eig(A)
pos_def = np.all(eigenValues > 0)
if (pos_def == True):
    print(A, '\nlà ma trận xác định dương.')
    print("UPPER Cholesky factor:\n", cholesky(A))
    print("UPPER Cholesky factor:\n", cholesky(A, check_finite = True))
else:
    print(A, '\nKHÔNG phải là ma trận xác định dương.')
    
# Positive SEMIDEFINITE (symmetric) matrix
#    A positive semidefinite matrix is a Hermitian matrix all of whose eigenvalues
#    are nonnegative.
A = np.array([[9, 6], [6, 4]])

# Eigenvalues
eigenValues, eigenVectors = la.eig(A)
pos_def = np.all(eigenValues > 0)
if (pos_def == True):
    print(A, '\nlà ma trận xác định dương.')
    print("UPPER Cholesky factor:\n", cholesky(A, check_finite = True))
else:
    print(A, '\nKHÔNG phải là ma trận xác định dương.')
    
# NOT Positive SEMIDEFINITE (symmetric) matrix
A = np.array([[9, 6], [6, 3]])

# Eigenvalues
eigenValues, eigenVectors = la.eig(A)
pos_def = np.all(eigenValues > 0)
if (pos_def == True):
    print(A, '\nlà ma trận xác định dương.')
    print("UPPER Cholesky factor:\n", cholesky(A, check_finite = True))
else:
    print(A, '\nKHÔNG phải là ma trận xác định dương.')



UPPER   Cholesky factor:
 [[2.44948974 0.40824829 0.40824829]
 [0.         2.41522946 0.34503278]
 [0.         0.         2.39045722]]
A:
 [[6. 1. 1.]
 [1. 6. 1.]
 [1. 1. 6.]]
UPPER   Cholesky factor:
 [[2.44948974 0.40824829 0.40824829]
 [0.         2.41522946 0.34503278]
 [0.         0.         2.39045722]]
LOWER   Cholesky factor:
 [[2.44948974 0.         0.        ]
 [0.40824829 2.41522946 0.        ]
 [0.40824829 0.34503278 2.39045722]]
A:
 [[6. 1. 1.]
 [1. 6. 1.]
 [1. 1. 6.]]
UPPER   Cholesky factor:
 [[ 2.          6.         -7.5       ]
 [ 0.          1.          3.        ]
 [ 0.          0.          5.72276157]]
A:
 [[  4.  12. -15.]
 [ 12.  37. -42.]
 [-15. -42.  98.]]
UPPER   Cholesky factor:
 [[ 2.          6.         -7.5       ]
 [ 0.          1.          3.        ]
 [ 0.          0.          5.72276157]]
LOWER   Cholesky factor:
 [[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]
A:
 [[  4.  12. -16.]
 [ 12.  37. -43.]
 [-16. -43.  98.]]
[[9 6]
 [6 5]] 
là ma trận xác định