In [1]:
"""=============================================================================
    Ex1: DECOMPOSITION
    Câu 1: LU Decomposition
        a) Tạo ma trận A(4 x 5) chứa các giá trị ngẫu nhiên trong khoảng 1 - 10
        b) Phân tích thành các thành phần P, L, U. In kết quả
        c) Tái tạo lại ma trận A từ các thành phần P, L, U
============================================================================="""
    
import numpy  as np
import random       
from scipy.linalg import lu

##------------------------------------------------------------------------------
## Hàm tạo 1 ma trận A[mxn] với giá trị ngẫu nhiên thuộc [start, end]
##------------------------------------------------------------------------------
def create_matrix_random(m, n, start, end):
    mtr = []
    for i in range(m):
        row = []
        for j in range(n):
            a = random.randint(start, end + 1)
            
            # Thêm giá trị vào dòng hiện hành 
            row.append(a)
            
        # Thêm dòng vào ma trận    
        mtr.append(row)
        
    return np.array(mtr)
##------------------------------------------------------------------------------

## a) Tạo ma trận A(4 x 5) chứa các giá trị ngẫu nhiên trong khoảng 1 - 10
## Ma trận HÌNH CHỮ NHẬT: A(m, n) = P_T(m, m).L(m, n).U(n, n)
m, n, min, max = 5, 4, 1, 10
A = create_matrix_random(m, n, min, max)
print('Ma trận A', A.shape, ':\n', A)

## b) Phân tích thành các thành phần P, L, U. In kết quả
P_T, L, U = lu(A)

print('Ma trận P_T', P_T.shape, ':\n', P_T)
print('Ma trận L', L.shape, ':\n', L)
print('Ma trận U', U.shape, ':\n', U)

## c) Tái tạo lại ma trận B từ các thành phần P, L, U
print('Tái tạo ma trận A:\n', P_T.dot(L).dot(U))


Ma trận A (5, 4) :
 [[ 2  1  8  2]
 [ 5  1  2  6]
 [ 9 11  7  2]
 [ 5  2  9  5]
 [ 3  3  5  1]]
Ma trận P_T (5, 5) :
 [[0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0.]]
Ma trận L (5, 4) :
 [[1.         0.         0.         0.        ]
 [0.55555556 1.         0.         0.        ]
 [0.22222222 0.2826087  1.         0.        ]
 [0.33333333 0.13043478 0.41744548 1.        ]
 [0.55555556 0.80434783 0.95015576 0.55371901]]
Ma trận U (4, 4) :
 [[ 9.         11.          7.          2.        ]
 [ 0.         -5.11111111 -1.88888889  4.88888889]
 [ 0.          0.          6.97826087  0.17391304]
 [ 0.          0.          0.         -0.37694704]]
Tái tạo ma trận A:
 [[ 2.  1.  8.  2.]
 [ 5.  1.  2.  6.]
 [ 9. 11.  7.  2.]
 [ 5.  2.  9.  5.]
 [ 3.  3.  5.  1.]]
